### ISSUE TITLE
考虑跨语言吗?

### ISSUE THREAD

**Issue by xiake999** [TeaMeow/Maxim#1]
您好,请问这个项目有考虑到跨语言吗? 
php,c#等等。 这些语言有websocket的类库,应该可以直接使用吧？

**Comment by YamiOdymel** [comment]
如果你指的是跨語言的 Client（客戶端），實作應該不會很難⋯⋯

但重點就在於我不會那麼多語言，所以實作上也就有障礙（不能像 [gRPC](https://grpc.io/) 那樣通吃各大語言），

變成說如果你要在其他語言上和 Golang 的 Maxim 伺服端（Server）進行溝通，

你需要自己建立一個 WebSocket（如透過 C#、Erlang、Python⋯⋯等），

然後透過 [MessagePack](msgpack.org) 編碼並透過 WebSocket 傳遞下列結構的內容到 Golang 端。

```js
{
    tid: int,     本次工作編號。
    fun: string,  欲呼叫的遠端函式名稱。
    met: ?object, 中繼資料內容。
    dat: ?object  主要資料內容。
}
```

然後還要監聽 WebSocket 所接收的訊息⋯⋯之類的。

這個項目現在比較偏向配合前端（JavaScript）和後端（Golang）所寫的。

**Comment by xiake999** [comment]
@YamiOdymel  谢谢,我已经完成c# client
